### ISSUE TITLE
Invalid page transition

### ISSUE THREAD

**Issue by mpppk** [mpppk/projegrid#21]
## Context

いろいろプルリクがマージされていたので、動作を確認しようとstaging環境を触ってみた
## Problem

スクリーンアカウントの登録時やログアウト時にlocalhost:3000へ飛ばされてしまう
## Solution(Optional)

config.urlにlocalhost:3000が指定されているのが原因
https://github.com/mpppk/projegrid/blob/master/config/config_common.js#L8

相対パスで遷移させればいい気がする(何か問題ありますか?)

**Comment by rice10t** [comment]
リダイレクトは相対パスでいいけど、API叩くときにはconfig.urlの値を元に指定したいのでできればconfig.urlはそのまま残しておきたいです。
config.urlも環境変数から取ってこれるように修正できるのならそっちの方が解決策としてはいいんじゃないかと思います。
